# Bootloader configuration for Luma Linux.
---
efiBootLoader: "grub"

timeout: "10"

grubInstall: "/usr/sbin/luma-grub-install"
grubMkconfig: "/usr/sbin/grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "/usr/sbin/grub-probe"
efiBootMgr: "/usr/bin/efibootmgr"

efiBootloaderId: "Luma"
installEFIFallback: false
